Create python-publish.yml
Arch4ngel21/scikit-fingerprints pull request #63
Opened 2023-12-13 18:51 UTC by przemekk6973

2023-12-14 14:05 UTC, j-adamczyk requested changes

2023-12-14 14:05 UTC, j-adamczyk commented on .github/workflows/python-publish.yml
> +    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
Remove emojis and shorten to "Buil and publish to PyPI" if possible

2023-12-14 14:05 UTC, j-adamczyk commented on .github/workflows/python-publish.yml
> +on: push
We don't want to publish on every master push, only when we tag a release. Maybe also only from a separate release branch. How is it handled here?

2023-12-14 14:05 UTC, j-adamczyk commented on .github/workflows/python-publish.yml
> +    runs-on: ubuntu-18.04
This is an old system. Can we run on 22, or at least 20?

2023-12-14 14:05 UTC, j-adamczyk commented on .github/workflows/python-publish.yml
> +      if: startsWith(github.ref, 'refs/tags')
This ensures that we only build and publish tagged releases?

2023-12-30 12:31 UTC, przemekk6973 commented
The publish on release action works, but testpypi doesn't allow to publish the same version of the library twice. Thats why the latest run failed. However, there is a succesful run in the actions history and when the newer version of library is published, everything will be fine. As far as the test scripts are concerned, after last week's changes, the e3fp tests do not work. We agreed with Piotrek to remove them for now, as the fingerprint needs fix in the future anyway. Once the test scripts are done, this PR is ready to merge.
![image](https://github.com/Arch4ngel21/scikit-fingerprints/assets/92885402/59e74507-9d44-409d-bb66-a951a644ad13)

2023-12-30 15:26 UTC, j-adamczyk requested changes

2023-12-30 15:26 UTC, j-adamczyk commented on pyproject.toml
> +ogb = "*"
This should not be a requirement. We do not use OGB in the library itself

2023-12-31 15:52 UTC, merged