Avalon Fingerprint
Arch4ngel21/scikit-fingerprints pull request #76
Opened 2024-01-24 14:29 UTC by my-alaska

RDKit's SparseIntVector cannot be directly converted to numpy or sparse array, therefore it forces our implementation to calculate a 2d python list that then gets converted to either sparse or numpy array. This could be considered suboptimal.

2024-01-24 14:43 UTC, j-adamczyk requested changes

2024-01-24 16:58 UTC, my-alaska commented on skfp/fingerprints/avalon.py
> +        count: bool = False,
done

2024-01-24 17:10 UTC, my-alaska commented on skfp/fingerprints/avalon.py
> +                for x in X
The `UIntSparseIntVect` has a `GetLength` that returns the number of bits in the sparse vector. It appears that on top of the data, the class also has a variable that holds the length of the vector:

`class UIntSparseIntVect(__Boost_Python.instance):
    """A container class for storing integer
    values within a particular range.
    
    The length of the vector is set at construction time.
    ...`

2024-01-24 17:13 UTC, my-alaska commented on benchmarking/benchmark.py
> +        "ErG fingerprint",
done

2024-01-25 14:29 UTC, j-adamczyk approved these changes

2024-01-25 14:34 UTC, merged